### ISSUE TITLE
It should be possible to re-provision a VM by doing an OS reload instead of a cancel

### ISSUE THREAD

**Issue by hairyhenderson** [softlayer/knife-softlayer#17]
It should be possible to re-provision a VM by doing an OS reload instead of a cancel.

i.e. I want something that acts like `knife softlayer server destroy ...`, except that instead of cancelling the VM through the SL API, it would instead do an OS reload.

**Comment by cphrmky** [comment]
@hairyhenderson,

Here's the feature branch if you'd like to take it for an early test drive and give any feedback you've got.

https://github.com/softlayer/knife-softlayer/tree/feature/server_relaunch

Usage is `knife softlayer server relaunch <NODE NAME>`.  That's going to relaunch the VM and bootstrap it from scratch, same node name, same attributes, etc.

/cc @underscorephil

**Comment by cphrmky** [comment]
@hairyhenderson ,

This has been merged and a release has been cut.  Upgrade to v0.3.12 to pick up this functionality.

/cc @underscorephil

**Comment by hairyhenderson** [comment]
@cphrmky - thanks! Sorry I never got around to test-driving it... Haven't had the cycles for this for a few weeks. :(

**Comment by cphrmky** [comment]
@hairyhenderson haha, no worries, I took it for a spin myself, of course other people are going to be better I finding the bugs I've written than I will...
