### ISSUE TITLE
VLAN options causing exceptions

### ISSUE THREAD

**Issue by hugespoon** [softlayer/knife-softlayer#19]
When specifying VLANs during `knife softlayer server create` the Fog::Service.validate_options method is returning an exception. Specifically the following,

`ERROR: ArgumentError: Missing required arguments: softlayer_username, softlayer_api_key`

It looks like this method is getting called twice (possibly for Network.new and Service.new although I'm not too familiar with Fog internals) and the requirements remain the same but the options hash is empty the second time around.

Using pry-stack_explorer I'm able to get the following:

    Showing all accessible frames in stack (18 in total):
    --
    => #0  validate_options <Fog::Service.validate_options(options)>
    #1 [method]  handle_settings <Fog::Service.handle_settings(settings)>
    #2 [method]  new <Fog::Service.new(config=?)>
    #3 [method]  new <Fog::Network.new(attributes)>
    #4 [method]  [] <Fog::Network.[](provider)>
    #5 [method]  vlan= <Fog::Compute::Softlayer::Server#vlan=(value)>
    #6 [block]   block in merge_attributes <Fog::Attributes::InstanceMethods#merge_attributes(new_attributes=?)>
    #7 [method]  merge_attributes <Fog::Attributes::InstanceMethods#merge_attributes(new_attributes=?)>
    #8 [method]  initialize <Fog::Model#initialize(new_attributes=?)>
    #9 [method]  initialize <Fog::Compute::Softlayer::Server#initialize(attributes=?)>
    #10 [method]  new <Fog::Collection#new(attributes=?)>
    #11 [method]  create <Fog::Collection#create(attributes=?)>
    #12 [method]  run <Chef::Knife::SoftlayerServerCreate#run()>
    #13 [method]  run_with_pretty_exceptions      <Chef::Knife#run_with_pretty_exceptions(raise_exception=?)>
    #14 [method]  run <Chef::Knife.run(args, options=?)>
    #15 [method]  run <Chef::Application::Knife#run()>
    #16 [top]     <top (required)>
    #17 [main]    <main>

The code ultimately raising the exception can be found at https://github.com/fog/fog-core/blob/master/lib/fog/core/service.rb#L236-L253 but perhaps https://github.com/fog/fog-softlayer/blob/master/lib/fog/softlayer/models/compute/server.rb#L201-L207 is the real culprit? As I said I haven't much dug into Fog ever, so this was where I ended up.

If you need any more info, just let me know. This one is thorny!

**Comment by hugespoon** [comment]
Here is my backtrace of the exception as well (e.backtrace)

    => ["/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/service.rb:246:in `validate_options'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/service.rb:270:in `handle_settings'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/service.rb:99:in `new'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/network.rb:16:in `new'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/network.rb:4:in `[]'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.26/lib/fog/softlayer/models/compute/server.rb:205:in `vlan='",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/attributes.rb:118:in `block in merge_attributes'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/attributes.rb:113:in `each_pair'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/attributes.rb:113:in `merge_attributes'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/model.rb:20:in `initialize'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-softlayer-0.3.26/lib/fog/softlayer/models/compute/server.rb:53:in `initialize'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/collection.rb:112:in `new'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/collection.rb:112:in `new'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/fog-core-1.27.2/lib/fog/core/collection.rb:49:in `create'",
    "/Users/hugespoon/.chefdk/gem/ruby/2.1.0/gems/knife-softlayer-0.3.6/lib/chef/knife/softlayer_server_create.rb:297:in `run'",
    "/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'",
    "/opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:174:in `run'",
    "/opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'",
    "/opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'",
    "/usr/bin/knife:33:in `load'",
    "/usr/bin/knife:33:in `<main>'"]

**Comment by hugespoon** [comment]
Just realized this could be related to https://github.com/softlayer/knife-softlayer/issues/12

**Comment by cphrmky** [comment]
@hugespoon ,

Agreed, looks like the same issue at least at first glance.  Can you confirm that creating a `~/.fog` file with softlayer credentials makes it go away?  That's both an immediate workaround as well as confirmation that it is being caused as per #12 .

Thanks.

**Comment by hugespoon** [comment]
Yeah, it did correct things for me.

**Comment by cphrmky** [comment]
@hugespoon thanks for letting me know.  So that's your workaround for now.  Marking this as a duplicate and closing it.  Will push a release with a fix today.

**Comment by cphrmky** [comment]
@hugespoon can you do me a favor reply with the `--various --arguments` you were using when you saw this error, I'm having trouble duplicating the error despite removing my `~/.fog` file.

**Comment by cphrmky** [comment]
@hugespoon never mind I've got it happening for me now.

**Comment by drag00n** [comment]
Might also be helpful to see your fog.yml file (with dummy values of course)

**Comment by hugespoon** [comment]
@cphrmky Sweet! Thanks for the quick fix.
