### ISSUE TITLE
use-private-network flag

### ISSUE THREAD

**Issue by sgiacomel** [softlayer/knife-softlayer#39]
We have an environment in SoftLayer with several VLANS. Port 22 is closed everywhere to the public, so we can ssh into the servers only when connected to the VPN. There's an option in the plugin (--use-private-network) that allows to bootstrap using the private interface. Unfortunately, it seems like the chef-client starts as soon as the connection becomes available regardless of the fact that the provisioning process is complete. In fact, the chef-client starts its execution but then a reboot signal comes from the provisioning, killing the chef-client execution. Any idea how to solve this?
Thanks

**Comment by cphrmky** [comment]
@sgiacomel 

For reference [here's the spot](https://github.com/softlayer/knife-softlayer/blob/master/lib/chef/knife/softlayer_server_create.rb#L308) where this plugin waits for the server to be ready and sshable.

If you're not familar with fog:

* `ready?` evaluates to true when the `server.state == 'running'` according to the SL api
* `sshable?` evaluates to true when the OS has booted and a test ssh connection has successfully been established 

Based on what you're describing and past experience I'm guessing that you've got some kind of post provisioning scripts calling for that reboot (maybe patching the kernel or something)?

Let me know if that's the case please and I'll see what I can do about detecting the presence of those scripts and if there's a way to know when they've completed.

In the meantime, if this is seriously blocking you, you can brute force the issue with something like [this workaround](https://github.com/softlayer/knife-softlayer/commit/ff8d8bf5119aa41c9dc6c4a84e94e292c4a06207)

**Comment by sgiacomel** [comment]
Based on what I see, it should just work fine. 
I don't have a post provisioning script that calls a reboot, I am just calling a simple chef recipes.
I'll do more investigation. 
Thanks for the answer.

**Comment by cphrmky** [comment]
Closing this issue for now.  Feel free to reopen it as needed.
