### ISSUE TITLE
Unable to find Uplink Port Speeds at  Mbps error while creating VM on the Softlayer

### ISSUE THREAD

**Issue by alkeshdagade** [softlayer/knife-softlayer#44]
We are trying to create a new VM using knife softlayer server create command. In the command if we include "network-interface-speed" parameter then getting below error. If we don't include network-interface-speed parameter while submitting request then we are able to create instance successfully on the SoftLayer. We tried to set network-interface-speed parameter values to 10, 100, 1000, 10000 but observed same error for all the values.  

ERROR: Excon::Error::InternalServerError: Expected([200, 201]) <=> Actual(500 InternalServerError)
excon.error.response
  :body          => "{\"error\":\"Unable to find Uplink Port Speeds at  Mbps.\",\"code\":\"SoftLayer_Exception_NotFound\"}"
 
Setup Versions details are as below:
OS: RHEL 7
Knife softlayer plugin version: 0.4.4
Chef version: 12.14.89

Please let me know if you need any other details.

**Comment by alkeshdagade** [comment]
Any update on this issue??

**Comment by cphrmky** [comment]
Sorry for the delay @alkeshdagade.

Can you tell me what version of the gem you're running?  You're on the latest which is `v0.4.4`?

This sounds like a problem that was resolved in the `v1.1.1` of fog-softlayer (one of the deps of this project).

**Comment by cphrmky** [comment]
eh sorry, just noticed that you had already included the version

that being the case, can you verify that your install is using `>=` `v1.1.1` of fog-softlayer?

**Comment by alkeshdagade** [comment]
Yes, I am on the latest one v0.4.4.

I downgraded gem version to 0.4.3, 0.4.2, 0.4.1 and with all these versions I observed same issue. When I used gem version as 0.4.0 then I was able to submit request successfully with nic parameter.

**Comment by alkeshdagade** [comment]
Install is using fog-softlayer version 1.1.4

**Comment by cphrmky** [comment]
hmmmm, paste me the complete `knife softlayer server create` command you're running?  (obviously redact/change anything you need to)  

I'm going to try to duplicate.

**Comment by alkeshdagade** [comment]
I am using command like this.

knife softlayer server create \
       --image-id $image_id \
       --ssh-keys $ssh_key_id \
       --hostname $host_name \
       --network-interface-speed 100 \
       --domain $domain_name \
       --cores 2 \
       --ram 4 \
       --datacenter ams01 \
       --node-name $host_name \
       --vlan $vlan_id \
       --private-vlan $private_vlan_id \
       --use-private-network \
       -x root \
       -i /home/.ssh/id_rsa

**Comment by cphrmky** [comment]
an update for you @alkeshdagade I have been able to reproduce, though I haven't yet gotten to the bottom of this, will keep you posted

**Comment by cphrmky** [comment]
okay I've got it figured, I'll cut a patch release shortly

**Comment by alkeshdagade** [comment]
You are quick Matt :)

Thanks for your help. I will wait for patch.

**Comment by cphrmky** [comment]
Just released `v0.4.5` which resolves this issue.  I tested it using more or less your above command with a value of `1000` for the uplink speed and it worked as expected.  Let me know if you encounter any more trouble with this.

**Comment by alkeshdagade** [comment]
Thanks a lot Matt for your help. I will check my script with 0.4.5 and let you know status.

**Comment by alkeshdagade** [comment]
I checked our script with latest build and now able to submit request along with NIC parameter. Thanks once again for your quick help.
