### ISSUE TITLE
API Question - Excon Error while provisioning server

### ISSUE THREAD

**Issue by viniciobombacino** [softlayer/knife-softlayer#60]
Hello, 

I'm getting the below error while provisioning servers using SOftlayer API. 
ERROR: Excon::Error::Socket: Connection reset by peer (Errno::ECONNRESET) 

We use the Knife Softlayer command to provision Servers as below: 
knife softlayer server create 
--image-id ${image_id} 
--ssh-keys ${ssh_keys} 
--hostname $node_name 
--network-interface-speed 100 
--domain $domain_name 
--cores ${cores} 
--ram ${ram} 
--datacenter ${datacenter} 
--node-name $node_name 
--vlan $public_vlan 
--private-vlan $private_vlan 
--use-private-network 
-x root 
-i $USER_HOME/.ssh/id_rsa 

The session throws an error after 6 minutes. 

The Softlayer's API seems to have an issue where sometimes the server resets the connection to the client. 

Could help me in resolving this issue?

**Comment by allmightyspiff** [comment]
Hello,

Sorry for taking a while to get around to this, I believe this is related to #61 . 

If you are still consistently having this problem, can you let me know what the debug trace looks like for that call? If your not comfortable posting that here, opening a support ticket with that information will also work.

**Comment by allmightyspiff** [comment]
This was resolved a bit ago, but for reference this was related to an upgrade we were doing. A misconfiguration in the newer loadbalancer caused some of these requests to be routed with a bad Host header. This only seems to have effected clients explicitly listing the port in the Host header, of which only the ruby client seems to be doing. 

Should all be working now though, so no worries there.
